export const articles = [
  {
    id: 1,
    title: 'Understanding Caching: A Simple Guide for Developers',
    date: 'May 04, 2025',
    datePublished: '2025-05-04',
    image: '/images/blogs/cache.jpg',
    excerpt: 'A practical introduction to caching strategies for backend developers, including in-memory, distributed, browser and database caching.',
    description: 'A practical introduction to caching strategies for backend developers, including in-memory, distributed, browser and database caching.',
  },
  {
    id: 2,
    title: '01 Matrix: BFS-Based Distance Calculation',
    date: 'June 23, 2025',
    datePublished: '2025-06-23',
    image: '/og-image.png',
    excerpt: 'A clear explanation of using multi-source breadth-first search to solve the 01 Matrix shortest-distance problem.',
    description: 'A clear explanation of using multi-source breadth-first search to solve the 01 Matrix shortest-distance problem.',
  },
  {
    id: 3,
    title: 'Tips for Clean JavaScript Code',
    date: 'April 20, 2025',
    datePublished: '2025-04-20',
    image: '/images/blogs/react.png',
    excerpt: 'Practical habits for writing JavaScript that is easier to read, review and maintain.',
    description: 'Practical habits for writing JavaScript that is easier to read, review and maintain.',
  },
  {
    id: 4,
    title: 'Designing for Developers',
    date: 'April 18, 2025',
    datePublished: '2025-04-18',
    image: '/images/blogs/react.png',
    excerpt: 'Notes on design decisions that help developers build clearer and more usable software interfaces.',
    description: 'Notes on design decisions that help developers build clearer and more usable software interfaces.',
  },
]
